//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsBrand
    {
        public MsBrand()
        {
            this.MsJewels = new HashSet<MsJewel>();
        }
    
        public int BrandId { get; set; }
        public string BrandName { get; set; }
        public string BrandCountry { get; set; }
        public string BrandClass { get; set; }
    
        public virtual ICollection<MsJewel> MsJewels { get; set; }
    }
}
