//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionHeader
    {
        public TransactionHeader()
        {
            this.TransactionDetails = new HashSet<TransactionDetail>();
        }
    
        public int TransactionId { get; set; }
        public int UserId { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string PaymentMethod { get; set; }
        public string TransactionStatus { get; set; }
    
        public virtual MsUser MsUser { get; set; }
        public virtual ICollection<TransactionDetail> TransactionDetails { get; set; }
    }
}
